@extends('layouts.app')

@section('content')
    @include('layouts.head')
    @include('layouts.finddomain')
    @include('layouts.prize')
    @include('layouts.service')
    @include('layouts.package')
    @include('layouts.vision')
    @include('layouts.makewebsite')
    @include('layouts.customer')
    @include('layouts.partner')
    @include('layouts.warranty')
    @include('layouts.comment')
    @include('layouts.payment')
    @include('layouts.cs')
    @include('layouts.footer')
@endsection
